/**
 * Structural implementation of the product's core data principle: every
 * monetary/derived figure returned by the API carries where it came from, so
 * the UI can render an Actual/Current/Estimated/Projected/AI-interpretation
 * badge directly from the payload instead of treating all numbers as equally
 * authoritative.
 *
 * - actual            verified, user-entered or DB-aggregated historical data
 * - current           retrieved from an external source "as of" a point in time
 * - estimated         calculated from actual/current data using stated assumptions
 * - projected         a future scenario, explicitly assumption-dependent
 * - ai_interpretation reasoning generated by the AI assistant (Phase 7+)
 */
export type ProvenanceTag =
  "actual" | "current" | "estimated" | "projected" | "ai_interpretation"

export interface ProvenanceValue<T> {
  value: T
  provenance: ProvenanceTag
  source: string
  asOf: string
  currency?: string
}

export function provenanceValue<T>(
  value: T,
  provenance: ProvenanceTag,
  source: string,
  options?: { currency?: string; asOf?: Date | string }
): ProvenanceValue<T> {
  const asOf = options?.asOf ?? new Date()
  return {
    value,
    provenance,
    source,
    currency: options?.currency,
    asOf: typeof asOf === "string" ? asOf : asOf.toISOString(),
  }
}

export function actual<T>(
  value: T,
  source = "database",
  currency?: string
): ProvenanceValue<T> {
  return provenanceValue(value, "actual", source, { currency })
}
